NAME = Bureaucrat
CPP = c++
CXXFLAGS = -Wall -Wextra -Werror -g3
FUN = 	Bureaucrat.cpp ShrubberyCreationForm.cpp AForm.cpp main.cpp


all :
	$(CPP) $(CXXFLAGS)  $(FUN) -o $(NAME)
clean : 
	rm -rf $(NAME)