NAME = Bureaucrat
CPP = c++
CXXFLAGS = -Wall -Wextra -Werror 
FUN = 	Bureaucrat.cpp RobotomyRequestForm.cpp AForm.cpp main.cpp


all :
	$(CPP) $(CXXFLAGS)  $(FUN) -o $(NAME)
clean : 
	rm -rf $(NAME)
	rm *_shrubbery