# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: bamssaye <bamssaye@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/03/08 02:51:22 by bamssaye          #+#    #+#              #
#    Updated: 2025/03/08 02:51:23 by bamssaye         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = Replace_world
CXX = c++
CXXFLAGS = -Wextra -Wall -Werror
FUN = *.cpp

all : $(NAME)

$(NAME) :
	$(CXX) $(CXXFLAGS) $(FUN) -o $(NAME)

clean :
	rm -rf $(NAME) $(OUTFILE)
re : clean all