# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: bamssaye <bamssaye@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/10/06 03:23:26 by bamssaye          #+#    #+#              #
#    Updated: 2025/03/03 00:01:42 by bamssaye         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = account
FUN = *.cpp
all : $(NAME)
$(NAME) : 
	c++ -Wall -Wextra -Werror -std=c++98 $(FUN) -o $(NAME)
clean :
	rm -rf $(NAME)
re : clean all
rr :
	@ft_lock
	@sleep 35m
	@kill -9 -1