NAME = Bureaucrat
CPP = c++
CXXFLAGS = -Wall -Wextra -Werror -std=c++98 #-fsanitize=address
FUN = 	Bureaucrat.cpp ShrubberyCreationForm.cpp RobotomyRequestForm.cpp PresidentialPardonForm.cpp Form.cpp Intern.cpp main.cpp 


all :
	$(CPP) $(CXXFLAGS)  $(FUN) -o $(NAME)
clean : 
	rm -rf $(NAME)
	rm -rf *_Shrubbery